### PR TITLE
Twitter clone project complete

### PR DESCRIPTION
**Pull request by joni-sadler**

### CODE REVIEW

**Comment by tiffanydow1** [comment]
When trying to run the project I'm getting an error saying that the index.html file is missing. This may have gotten removed accidentally.

**Comment by joni-sadler** [comment]
Hey Tiffany! Should I try to re-push my project to ensure the index.html
file is entered correctly?

**Comment by tiffanydow1** [comment]
Yes, maybe try that and see if that works!

**Comment by joni-sadler** [comment]
I've just re-added it to github. Let me know if this works? Sorry for the
hassle!

**Comment by tiffanydow1** [comment]
Great job with the project! I did notice I wasn't able to like tweets but other than that everything else looked good!

**Pull request closed without merging**
